name: Get package full tag to docker build
on: 
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        description: 'The name of the docker username.
        required: false

    outputs:
      full_tag:
        description: 'Full tag to use on a docker build'
        value: ${{ jobs.get_tag_docker.outputs.full_docker_tag }}

jobs:
  get_tag_docker:
    runs-on: [ubuntu-latest]
    outputs:
      full_docker_tag: ${{ steps.tagger.outputs.full_image_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get full image name
        uses: ./.github/actions/get-tag-docker-action
        id: tagger
        with:
          image_name: "${{ env.DOCKER_USERNAME }}/miau"
          version: ${{ nico }}