name: Build and Push Docker Image
on: [push,workflow_dispatch]

jobs:
  get_version:
    uses: ./.github/workflows/mi_reusable.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

  build:
    runs-on: [ubuntu-latest]
    needs: get_version

    steps:
      - name: Debug - mostrar tag recibido desde reusable workflow
        run: |
          echo "📦 Tag recibido desde reusable workflow: '${{ needs.get_version.outputs.full_tag }}'"
        shell: bash
    